# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Katuma
email: info@katuma.org
description: >- # this means to ignore newlines until "baseurl:"
  La plataforma cooperativa de consum de proximitat.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# social
social_media:
  - service: github
    user: coopdevs
    desc: Katuma Ã©s codi lliure
  - service: twitter
    user: katuma_org
    desc: Segueix-nos a Twitter
  - service: facebook
    user: katumaorg
    desc: Segueix-nos a Facebook

links:
  guide: https://guia.katuma.org/
  community: https://community.coopdevs.org/c/katuma
  app_signup: https://app.katuma.org/register/auth#/signup?after_login=%2Fregister
  org_signup: https://forms.coopdevs.org/index.php?r=survey/index&sid=224965&lang=ca
  ofn: https://openfoodnetwork.org/
  repository: https://github.com/openfoodfoundation/openfoodnetwork

# Build settings
markdown: kramdown
theme:
plugins:

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
